name: CD
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.10.0
      - run: npm ci
      - run: npm run lint
      - run: npm run export
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS }}
          aws-secret-access-key: ${{ secrets.S3_SECRET }}
          aws-region: us-west-2
      - run: aws s3 sync ./out s3://swft-marketing-site

